spring.application.name=TallerCrud

spring.datasource.url=jdbc:mysql://localhost:3306/tallercrud?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

# Permite servir archivos estáticos (index.html, CSS, JS)
spring.web.resources.add-mappings=true

# Activa el lanzamiento de excepción si una ruta NO existe
spring.mvc.throw-exception-if-no-handler-found=true